# Site settings
title: Stijn van Weezel    
email: vanweezel (at) pm.me
description: > # this means to ignore newlines until "baseurl:"
  Research and teaching material
# baseurl: "/" # the subpath of your site, e.g. /blog/
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
