# Site settings
title: Stijn van Weezel
email: stijn.vanweezel (at) ucd.ie
description: > # this means to ignore newlines until "baseurl:"
  Research and teaching material
# baseurl: "/" # the subpath of your site, e.g. /blog/
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
